import {IPublisher} from '../interfaces/table.interface';
export const ELEMENT_DATA: IPublisher[] = [
    {position: 1, name: 'Hydrogen', weight: 1.0079, symbol: 'H'},
    {position: 2, name: 'Helium', weight: 4.0026, symbol: 'He'},
    {position: 3, name: 'Lithium', weight: 6.941, symbol: 'Li'},
    {position: 4, name: 'Beryllium', weight: 9.0122, symbol: 'Be'},
    {position: 5, name: 'Boron', weight: 10.811, symbol: 'B'},
    {position: 6, name: 'Carbon', weight: 12.0107, symbol: 'C'},
    {position: 7, name: 'Nitrogen', weight: 14.0067, symbol: 'N'},
    {position: 8, name: 'Oxygen', weight: 15.9994, symbol: 'O'},
    {position: 9, name: 'Fluorine', weight: 18.9984, symbol: 'F'},
    {position: 10, name: 'Neon', weight: 20.1797, symbol: 'Ne'},
    {position: 11, name: 'Mauricio', weight: 20.1797, symbol: 'Mc'},
  ];

  

  const publishers = [
    { id:1, group: 1, name: "Reynaldo Demetrio Ramirez Guarate"},
    { id:2, group: 1, name: "Ana Rosa Ramirez (Noriega Cavadia)"},
    { id:3, group: 1, name: "Samuel Enrique Ramirez Rodriguez"},
    { id:4, group: 1, name: "Dianis Beatriz Blanchard"},
    { id:5, group: 1, name: "Hernan Calderon Garcia"},
    { id:6, group: 1, name: "Jaime Alexis Sanchez Moreno"},
    { id:7, group: 1, name: "Diana Marcela Sanchez (Vazquez Castro)"},
    { id:8, group: 1, name: "Emily Daniela Sanchez Vazquez"},
    { id:9, group: 1, name: "Gloria Amparo Orduz (Cadena Rios)"},
    { id:10, group:	1, name: "Maria Gloria Martinez (Sanchez Diaz)"},
    { id:11, group:	1, name: "Arselia Castiblanco (Salinas Fajardo)"},
    { id:12, group:	1, name: "Amparo De Jesus Foronda Meneses"},
    { id:13, group:	1, name: "Angela Maria Foronda Meneses"},
    { id:14, group:	1, name: "Cecilia Chaguala (Yate Bahamon)"},
    { id:15, group:	1, name: "Rita Helena Noriega Cavadia"},
    { id:16, group:	1, name: "Candelaria Gonzalez (Quiceno Sala)"},
    { id:17, group:	1, name: "Orlando Valero Cruz"},
    { id:18, group:	1, name: "Johana Astrid Valero (Zarate Rozo)"},
    { id:19, group:	1, name: "Simon Alberto Carrero Vega"},
    { id:20, group:	1, name: "Mailber Carrero (Moreno Muñoz)"},
    { id:21, group:	1, name: "Mayerli Quintero (Sanchez Ruiz)"},
    { id:22, group:	1, name: "Jose David Vera Noriega"},
    { id:23, group:	1, name: "Martha Consuelo Perez (Meneses Benavidez)"},
    { id:24, group:	1, name: "Bryan Daniel Valero Zarate"},
    { id:25, group:	1, name: "Maria (Mama De Candelaria) (Salas)"},
    { id:26, group:	1, name: "Leidys Miyarsy Molina (Andrades)"},
    { id:27, group:	1, name: "Coraline Quintero"},
    { id:28, group:	1, name: "Leila Martinez (Muñoz )"},
    { id:29, group:	1, name: "Beatriz Mata (Vargas)"},
    { id:30, group:	1, name: "Dimas Jose Mata Gonzalez"},
    { id:31, group:	1, name: "Keila Mata"},
    { id:32, group:	1, name: "Yulibeth Vanegas"},
    { id:33, group:	2, name: "Rosalia Casas (Ballen Ariza)"},
    { id:34, group:	2, name: "Maria Ramos Ariza"},
    { id:35, group:	2, name: "Martha Cecilia Oviedo (Medina Ardila)"},
    { id:36, group:	2, name: "Jessica Alexandra Oviedo (Chavez Baquero)"},
    { id:37, group:	2, name: "Jesus Arturo Oviedo Sanchez"},
    { id:38, group:	2, name: "Mabel Duran (Garcia Mosquera)"},
    { id:39, group:	2, name: "Elsa Gonzalez"},
    { id:40, group:	2, name: "Isabel Munard"},
    { id:41, group:	2, name: "Fabiola Millan"},
    { id:42, group:	2, name: "Carmenza Garcia"},
    { id:43, group:	2, name: "Elsa Maria Herrera (Dimate)"},
    { id:44, group:	2, name: "Jefferson Sebastian Castro Perez"},
    { id:45, group:	2, name: "Berenice Castro (Herrera Dimate)"},
    { id:46, group:	2, name: "Rafael Mosquera Valles"},
    { id:47, group:	2, name: "Sandra Regina Mosquera (Gutierrez Hernandez)"},
    { id:48, group:	2, name: "Flor Alba Cupitra"},
    { id:49, group:	2, name: "Luis Alberto Rincon Lopez"},
    { id:50, group:	2, name: "Sandra Patricia Rincon (Lopez Ospina)"},
    { id:51, group:	2, name: "Sandra Tatiana Rincon Lopez"},
    { id:52, group:	2, name: "Sindy Vanesa Rincon Lpez"},
    { id:53, group:	2, name: "Luis Felipe Rincon Lopez"},
    { id:54, group:	2, name: "Benilda Del Carmen Tapia De Agustin"},
    { id:55, group:	2, name: "Mibel Salgado Tapia"},
    { id:56, group:	2, name: "Ricardo Niño"},
    { id:57, group:	2, name: "Mariana Niño (Cantillo)"},
    { id:58, group:	2, name: "Victor Manuel Ortega"},
    { id:59, group:	2, name: "Meidy Coromoto Ortega (Finol)"},
    { id:60, group:	2, name: "Teresa Pachon (Mendoza)"},
    { id:61, group:	2, name: "Luis Carlos Pachon Mendoza Jr."},
    { id:62, group:	2, name: "Mateo Pachon Mendoza"},
    { id:63, group:	2, name: "Maryeri Ortiz Mendoza"},
    { id:64, group:	2, name: "Maria Rosa Junca Rincon"},
    { id:65, group:	2, name: "Nathaly Pachon"},
    { id:66, group:	2, name: "Aura Marina Ahumada Pretel"},
    { id:67, group:	2, name: "Jade Nathalie Duran Garcia"},
    { id:68, group:	3, name: "Jose Mauricio Casas Ballen"},
    { id:69, group:	3, name: "Nathalie Marcela Casas (Rojas Suesca)"},
    { id:70, group:	3, name: "Hector Garcia"},
    { id:71, group:	3, name: "Windsor Cuervo"},
    { id:72, group:	3, name: "Luz Marina Cuervo"},
    { id:73, group:	3, name: "Melba Barrero"},
    { id:74, group:	3, name: "Sindy Johana Barrero"},
    { id:75, group:	3, name: "Wilson Alberto Salazar"},
    { id:76, group:	3, name: "Adriana Salazar (Barrero)"},
    { id:77, group:	3, name: "Wilson Nicolas Salazar Barrero"},
    { id:78, group:	3, name: "Camilo Andres Salazar Barrero"},
    { id:79, group:	3, name: "Noris Olga Escarraga (Velasco)"},
    { id:80, group:	3, name: "Edwin Jimenez"},
    { id:81, group:	3, name: "Carmen Cecilia Ruiz"},
    { id:82, group:	3, name: "Lizeth Natalia Reyes Ruiz"},
    { id:83, group:	3, name: "Luis Alberto Niño Larrotta"},
    { id:84, group:	3, name: "Yuliana Niño ()"},
    { id:85, group:	3, name: "Hasbleidy Lozano ()"},
    { id:86, group:	3, name: "Gabriela Parra"},
    { id:87, group:	3, name: "Amparo Larrota"},
    { id:88, group:	3, name: "Carlos Albeiro Sanchez"},
    { id:89, group:	3, name: "Maria Emilia Atehortua"},
    { id:90, group:	3, name: "Diana Esperanza Niño Larrotta"},
    { id:91, group:	3, name: "Fernando Ceballos"},
    { id:92, group:	3, name: "Lesley Avella (Gonzalez)"},
    { id:93, group:	3, name: "Vanesa Gonzalez"},
    { id:94, group:	3, name: "Ignacio Avella"},
    { id:95, group:	3, name: "Angie Avella ()"},
    { id:96, group:	3, name: "Santiago Avella"},
    { id:97, group:	3, name: "Yeimer Fabian Salazar"},
    { id:98, group:	3, name: "Kelly Salazar ()"},
    { id:99, group:	3, name: "Yeison Orjuela"},
    { id: 100, group:4,	name: "Janneth Rocio Chavez (Baquero)"},
    { id: 101, group:4,	name: "Leidy Leiva"},
    { id: 102, group:4,	name: "Jose Fernely Valencia Arenas"},
    { id: 103, group:4,	name: "Gerson David Valencia Gandia"},
    { id: 104, group:4,	name: "Yolis De Jesus Valencia (Gandia Perez)"},
    { id: 105, group:4,	name: "Karen Nataly Jaramillo Rueda"},
    { id: 106, group:4,	name: "Cielo Lady Vargas (Vargas Suarez)"},
    { id: 107, group:4,	name: "N3talia Estefania Vargas Vargas"},
    { id: 108, group:4,	name: "Dana Sofia Vargas Vargas"},
    { id: 109, group:4,	name: "Paola Pereira"},
    { id: 110, group:4,	name: "Flor Marina Diaz"},
    { id: 111, group:4,	name: "Claudia Silva (Monsalve Ceina)"},
    { id: 112, group:4,	name: "Ingrid Daniela Toro Monsalve"},
    { id: 113, group:4,	name: "Ander David Silva Monsalve"},
    { id: 114, group:4,	name: "Edwin David Guzman Mendoza"},
    { id: 115, group:4,	name: "Dayana Guzman (Poveda Trespalacios)"},
    { id: 116, group:4,	name: "Linalba Pineda"},
    { id: 117, group:4,	name: "Gustavo Carrillo"},
    { id: 118, group:4,	name: "Gustavo Abril"},
    { id: 119, group:4,	name: "Marleny Carrillo ()"},
    { id: 120, group:4,	name: "Leticia Rincon (Briñez)"},
    { id: 121, group:4,	name: "Jorge Chavez"},
    { id: 122, group:4,	name: "Juan Carlos Vera"},
    { id: 123, group:4,	name: "Marisol Vera ()"},
    { id: 124, group:4,	name: "Brandon Pineda"},
    { id: 125, group:4,	name: "Angie Marcela Vera (Bonilla Correa)"},
    { id: 126, group:4,	name: "Kelvin Alexander Vera Quiroz"},
    { id: 127, group:5,	name: "Wilson Ramos Walteros"},
    { id: 128, group:5,	name: "Yuri Carolina Ramos (Guitierrez Soler)"},
    { id: 129, group:5,	name: "Karen Sofia Ramos Martinez"},
    { id: 130, group:5,	name: "Gloria Ines Cortez"},
    { id: 131, group:5,	name: "Sara Maria Cortez"},
    { id: 132, group:5,	name: "Alba Lucia Guzman (Mendoza Malagon)"},
    { id: 133, group:5,	name: "Drelfi Esteban Guzman Mendoza"},
    { id: 134, group:5,	name: "Mariela Castro Tellez"},
    { id: 135, group:5,	name: "Maria Del Transito Peña (Ramirez Rodriguez)"},
    { id: 136, group:5,	name: "Elber Peña Cortez"},
    { id: 137, group:5,	name: "Isabel Cortes (Pacheco )"},
    { id: 138, group:5,	name: "Tulia Tolentino"},
    { id: 139, group:5,	name: "Ana Isabel Lozano Caicedo"},
    { id: 140, group:5,	name: "Zoraida Leiton (Benavides )"},
    { id: 141, group:5,	name: "Drelfi Guzman Perilla"},
    { id: 142, group:5,	name: "Marleny Corrales"},
    { id: 143, group:5,	name: "Ana Pino"},
    { id: 144, group:5,	name: "Paola Prieto"},
    { id: 145, group:5,	name: "Danilo Gonzalez"},
    { id: 146, group:5,	name: "Adriana Gonzalez (Enriquez)"},
    { id: 147, group:5,	name: "Nora Guzman"},
    { id: 148, group:5,	name: "Miryan Contreras Aranda"},
    { id: 149, group:5, name: "Rosmira Pino"}
  ]